spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          digitalregisteredletter:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          messagingsettings:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          messaging:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          employee:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          digitalregisteredletter:
            client-id: the-client-id
            client-secret: the-client-secret
          messagingsettings:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
          employee:
            client-id: the-client-id
            client-secret: the-client-secret
integration:
  citizen:
    url: http://localhost:${wiremock.server.port:}/api-citizen
  digitalregisteredletter:
    url: http://localhost:${wiremock.server.port:}/api-digitalregisteredletter
  messagingsettings:
    url: http://localhost:${wiremock.server.port:}/api-messagingsettings
  messaging:
    url: http://localhost:${wiremock.server.port:}/api-messaging
  employee:
    url: http://localhost:${wiremock.server.port:}/api-employee
