spring:
  flyway:
    enabled: true
  cache:
    type: none
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://token.url
          digitalregisteredletter:
            token-uri: http://token.url
          messagingsettings:
            token-uri: http://token.url
          messaging:
            token-uri: http://token.url
          employee:
            token-uri: http://token.url
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          digitalregisteredletter:
            client-id: the-client-id
            client-secret: the-client-secret
          messagingsettings:
            client-id: the-client-id
            client-secret: the-client-secret
          messaging:
            client-id: the-client-id
            client-secret: the-client-secret
          employee:
            client-id: the-client-id
            client-secret: the-client-secret
integration:
  citizen:
    url: http://citizen.local
    connect-timeout: 10
    read-timeout: 20
  digitalregisteredletter:
    url: http://digitalregisteredletter.local
    connect-timeout: 10
    read-timeout: 20
  messagingsettings:
    url: http://messagingsettings.local
    connect-timeout: 10
    read-timeout: 20
  messaging:
    url: http://messaging.local
    connect-timeout: 10
    read-timeout: 20
  employee:
    url: http://employee.local
    connect-timeout: 10
    read-timeout: 20
