spring:
  main:
    banner-mode: off
  application:
    name: api-service-postportalservice
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE.URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
  security:
    oauth2:
      client:
        registration:
          digitalregisteredletter:
            authorization-grant-type: client_credentials
            provider: digitalregisteredletter
openapi:
  title: Postportalservice
  name: postportalservice
  version: '@project.version@'
